# Generated by Django 5.2.3 on 2025-06-27 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_address_alter_member_dob_and_more'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='trainers.trainer'),
        ),
    ]
