# Generated by Django 5.2.3 on 2025-06-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20250628_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='member_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
