# Generated by Django 5.2.3 on 2025-06-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_payment_member_email'),
    ]

    operations = [
    ]
