from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import MemberViewSet

router = DefaultRouter()
router.register(r'members', MemberViewSet)

urlpatterns = [
    path('', include(router.urls)),
]
# This code sets up the URL routing for the members app in a Django project.
# It uses Django REST Framework's DefaultRouter to automatically generate the URL patterns for the MemberViewSet.
# The `include(router.urls)` function includes all the URLs generated by the router, which will
# handle requests to the members API endpoints.